version: '3'
services:
  book_catalog:
    image: book_catalog:latest
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
      args:
        - NO_CACHE=true
    container_name: book_catalog_cntr
    ports:
     - "4002:5000"
    environment:
      - PORT=5000
      - DATABASE_URL= postgresql://manish_project_part3_k9ky_user:Ug5DGyVIHEzLPE7mEAql15jTWrFaESd2@dpg-crgitp2j1k6c739icpmg-a.oregon-postgres.render.com/manish_project_part3_k9ky
    restart: "no"

  inventory_management:
    image: inventory_management:latest
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
      args:
        - NO_CACHE=true
    container_name: inventory_management_cntr
    ports:
     - "4003:5001"
    environment:
      - PORT=5001
      - DATABASE_URL= postgresql://manish_project_part3_k9ky_user:Ug5DGyVIHEzLPE7mEAql15jTWrFaESd2@dpg-crgitp2j1k6c739icpmg-a.oregon-postgres.render.com/manish_project_part3_k9ky
    restart: "no"
