version: '3'
services:
  book_catalog:
    image: book_catalog:latest
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog_cntr
    ports:
     - "4010:5010"
    environment:
      - PORT=5010
      - DATABASE_URL=postgresql://manish_project_part3_yn1w_user:BuFAtim9mJ0hIPSKTKMpvTgH4cowDier@dpg-crg2nk3v2p9s73a6cir0-a.oregon-postgres.render.com/manish_project_part3_yn1w
    restart: "no"

  inventory_management:
    image: inventory_management:latest
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management_cntr
    ports:
     - "4020:5020"
    environment:
      - PORT=5020
      - DATABASE_URL=postgresql://manish_project_part3_yn1w_user:BuFAtim9mJ0hIPSKTKMpvTgH4cowDier@dpg-crg2nk3v2p9s73a6cir0-a.oregon-postgres.render.com/manish_project_part3_yn1w
    restart: "no"
